"""Deterministic, local repository inventory and durable agent documentation."""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
import tomllib
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

from .detectors.dotnet import inspect_dotnet_project


LANGUAGE_EXTENSIONS = {
    ".cs": "C#", ".py": "Python", ".ts": "TypeScript", ".tsx": "TypeScript",
    ".js": "JavaScript", ".jsx": "JavaScript", ".java": "Java",
    ".go": "Go", ".php": "PHP", ".rb": "Ruby",
}
IGNORED_DIRECTORIES = {
    ".git", ".venv", "venv", "bin", "obj", "node_modules", "dist", "build", ".vs",
}


MAP_NAME = "REPOSITORY_MAP.md"
MAP_MARKER = "<!-- generated by repository-mapper; do not edit this file by hand -->"
REFERENCE_START = "<!-- repository-map reference: start -->"
REFERENCE_END = "<!-- repository-map reference: end -->"
MANIFEST_NAMES = {
    "package.json", "pyproject.toml", "requirements.txt", "go.mod", "pom.xml",
    "build.gradle", "build.gradle.kts", "dockerfile", "compose.yaml",
    "compose.yml", "docker-compose.yml", "docker-compose.yaml", "makefile",
    "cargo.toml", "gemfile", "composer.json", "azure-pipelines.yml",
    "jenkinsfile", ".gitlab-ci.yml",
}
ENTRY_NAMES = {
    "program.cs", "startup.cs", "main.py", "app.py", "manage.py",
    "main.go", "index.ts", "index.js", "server.ts", "server.js",
}
COMPONENT_NAMES = {
    "controllers": "controllers", "services": "services", "repositories": "repositories",
    "workers": "workers", "handlers": "handlers", "consumers": "consumers",
    "migrations": "migrations", "models": "models", "entities": "entities",
    "tests": "tests", "test": "tests",
}
MAX_FILES = 50_000
MAX_MANIFEST_BYTES = 512_000
MAX_COMPONENT_PATHS = 30


def _git(root: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-c", f"safe.directory={root.as_posix()}", "-C", str(root), *args],
            capture_output=True, check=False, timeout=45,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        raise ValueError(f"Git is unavailable for {root}: {exc}") from exc
    if result.returncode:
        error = result.stderr.decode("utf-8", errors="replace").strip()
        raise ValueError(f"Git failed in {root}: {error or 'unknown error'}")
    return result.stdout.decode("utf-8", errors="replace")


def _root(repo_path: str) -> Path:
    if not repo_path or not Path(repo_path).is_absolute():
        raise ValueError("repo_path must be an absolute Git repository root")
    root = Path(repo_path).resolve(strict=True)
    if not root.is_dir():
        raise ValueError(f"Not a directory: {root}")
    git_root = Path(_git(root, "rev-parse", "--show-toplevel").strip()).resolve()
    if git_root != root:
        raise ValueError(f"Pass the repository root, not a subdirectory: {git_root}")
    return root


def _safe_name(path: Path) -> bool:
    if any(part.lower() in IGNORED_DIRECTORIES for part in path.parts):
        return False
    name = path.name.lower()
    if name.startswith(".env") or path.suffix.lower() in {".pem", ".p12", ".pfx", ".key"}:
        return False
    return not (any(word in name for word in ("credential", "secret", "private-key"))
                and path.suffix.lower() not in LANGUAGE_EXTENSIONS)


def _files(root: Path) -> tuple[list[Path], list[str]]:
    # Include local untracked, non-ignored files: a new project may not be committed yet.
    raw = _git(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
    paths: list[Path] = []
    for value in raw.split("\0"):
        if not value:
            continue
        relative = Path(value)
        if not _safe_name(relative) or relative.as_posix() in {MAP_NAME, "AGENTS.md", "CLAUDE.md"}:
            continue
        candidate = (root / relative).resolve()
        if candidate.is_relative_to(root) and candidate.is_file():
            paths.append(relative)
    paths = sorted(set(paths), key=lambda item: item.as_posix().casefold())
    warnings = []
    if len(paths) > MAX_FILES:
        warnings.append(f"File inventory truncated at {MAX_FILES} of {len(paths)} files.")
        paths = paths[:MAX_FILES]
    return paths, warnings


def _display(value: object) -> str:
    """Keep repository-supplied metadata on one inert Markdown line."""
    return " ".join(str(value).replace("`", "'").split())


def _code(value: object) -> str:
    return f"`{_display(value)}`"


def _manifest_paths(paths: list[Path]) -> list[Path]:
    return [
        path for path in paths
        if path.suffix.lower() in {".csproj", ".sln", ".slnx"}
        or path.name.lower() in MANIFEST_NAMES
        or (len(path.parts) >= 3 and path.parts[0] == ".github" and path.parts[1] == "workflows")
    ]


def _safe_manifest(root: Path, relative: Path) -> Path | None:
    target = (root / relative).resolve()
    if not target.is_relative_to(root) or not target.is_file() or target.stat().st_size > MAX_MANIFEST_BYTES:
        return None
    return target


def _dependency_name(value: str) -> str | None:
    if "://" in value or value.startswith(("-", "git+")):
        return None
    match = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", value.strip())
    return match.group() if match else None


def _xml_name(element: ET.Element) -> str:
    return element.tag.rsplit("}", 1)[-1]


def _xml_child_text(element: ET.Element, name: str) -> str | None:
    return next((child.text.strip() for child in element
                 if _xml_name(child) == name and child.text), None)


def inspect_repository(repo_path: str) -> dict:
    """Collect facts from Git and safe manifest metadata; never write files."""
    root = _root(repo_path)
    paths, warnings = _files(root)
    languages = Counter(
        LANGUAGE_EXTENSIONS[path.suffix.lower()]
        for path in paths if path.suffix.lower() in LANGUAGE_EXTENSIONS
    )
    layout = Counter(
        "/".join(path.parts[:2]) if len(path.parts) > 2 and path.parts[0].lower() in {
            "src", "test", "tests", "services", "apps", "packages"
        } else (path.parts[0] if len(path.parts) > 1 else "(root)")
        for path in paths
    )
    components = Counter(
        label for path in paths
        for label in {COMPONENT_NAMES[part.lower()] for part in path.parts[:-1]
                      if part.lower() in COMPONENT_NAMES}
    )
    component_paths: dict[str, list[str]] = {}
    for path in paths:
        for label in {COMPONENT_NAMES[part.lower()] for part in path.parts[:-1]
                      if part.lower() in COMPONENT_NAMES}:
            component_paths.setdefault(label, []).append(path.as_posix())
    manifests = _manifest_paths(paths)
    projects: list[dict] = []
    node_packages: list[dict] = []
    python_projects: list[dict] = []
    python_requirements: list[dict] = []
    go_modules: list[dict] = []
    maven_projects: list[dict] = []
    for relative in manifests:
        if relative.suffix.lower() == ".csproj":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe project file: {relative.as_posix()}")
                continue
            try:
                project = inspect_dotnet_project(target)
            except (ET.ParseError, OSError, ValueError) as exc:
                warnings.append(f"Could not parse {relative.as_posix()}: {type(exc).__name__}")
                continue
            projects.append({
                "path": relative.as_posix(), "sdk": project.sdk,
                "target_framework": project.target_framework,
                "type": project.project_type, "test_framework": project.test_framework,
                "references": project.project_references,
                "packages": sorted({item.name for item in project.package_references}, key=str.casefold),
            })
        elif relative.name.lower() == "package.json":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe package file: {relative.as_posix()}")
                continue
            try:
                data = json.loads(target.read_text(encoding="utf-8"))
                if not isinstance(data, dict):
                    raise ValueError("expected object")
                dependencies = data.get("dependencies") or {}
                dev_dependencies = data.get("devDependencies") or {}
                if not isinstance(dependencies, dict) or not isinstance(dev_dependencies, dict):
                    raise ValueError("dependencies must be objects")
                node_packages.append({
                    "path": relative.as_posix(), "name": data.get("name"),
                    "dependencies": sorted(dependencies, key=str.casefold),
                    "dev_dependencies": sorted(dev_dependencies, key=str.casefold),
                })
            except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
                warnings.append(f"Could not parse {relative.as_posix()}: {type(exc).__name__}")
        elif relative.name.lower() == "pyproject.toml":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe Python manifest: {relative.as_posix()}")
                continue
            try:
                data = tomllib.loads(target.read_text(encoding="utf-8"))
                project = data.get("project", {})
                poetry = data.get("tool", {}).get("poetry", {})
                dependencies = project.get("dependencies", [])
                poetry_dependencies = poetry.get("dependencies", {})
                if not isinstance(dependencies, list) or not isinstance(poetry_dependencies, dict):
                    raise ValueError("invalid Python dependencies")
                # Keep only package names; versions and source URLs can contain credentials.
                names = [_dependency_name(item) for item in dependencies if isinstance(item, str)]
                names.extend(name for name in poetry_dependencies if name.lower() != "python")
                python_projects.append({
                    "path": relative.as_posix(), "name": project.get("name") or poetry.get("name"),
                    "requires_python": project.get("requires-python"),
                    "build_backend": data.get("build-system", {}).get("build-backend"),
                    "dependencies": sorted({name for name in names if name}, key=str.casefold),
                })
            except (OSError, UnicodeError, tomllib.TOMLDecodeError, ValueError, AttributeError) as exc:
                warnings.append(f"Could not parse {relative.as_posix()}: {type(exc).__name__}")
        elif relative.name.lower() == "requirements.txt":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe Python requirements: {relative.as_posix()}")
                continue
            try:
                names = [_dependency_name(line) for line in target.read_text(encoding="utf-8").splitlines()
                         if line.strip() and not line.lstrip().startswith("#")]
                python_requirements.append({
                    "path": relative.as_posix(),
                    "dependencies": sorted({name for name in names if name}, key=str.casefold),
                })
            except (OSError, UnicodeError) as exc:
                warnings.append(f"Could not read {relative.as_posix()}: {type(exc).__name__}")
        elif relative.name.lower() == "go.mod":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe Go manifest: {relative.as_posix()}")
                continue
            try:
                lines = target.read_text(encoding="utf-8").splitlines()
                module = next((line.removeprefix("module ").strip() for line in lines if line.startswith("module ")), None)
                dependencies = []
                in_require = False
                for line in lines:
                    stripped = line.strip()
                    if stripped == "require (":
                        in_require = True
                    elif in_require and stripped == ")":
                        in_require = False
                    elif stripped.startswith("require ") or (in_require and stripped and not stripped.startswith("//")):
                        value = stripped.removeprefix("require ").split()
                        if value:
                            dependencies.append(value[0])
                go_modules.append({
                    "path": relative.as_posix(), "module": module,
                    "dependencies": sorted(set(dependencies), key=str.casefold),
                })
            except (OSError, UnicodeError) as exc:
                warnings.append(f"Could not read {relative.as_posix()}: {type(exc).__name__}")
        elif relative.name.lower() == "pom.xml":
            target = _safe_manifest(root, relative)
            if target is None:
                warnings.append(f"Skipped large or unsafe Maven manifest: {relative.as_posix()}")
                continue
            try:
                xml_root = ET.parse(target).getroot()
                modules = [child.text.strip() for container in xml_root if _xml_name(container) == "modules"
                           for child in container if _xml_name(child) == "module" and child.text]
                dependencies = []
                for container in xml_root.iter():
                    if _xml_name(container) != "dependencies":
                        continue
                    for dependency in container:
                        if _xml_name(dependency) != "dependency":
                            continue
                        group = _xml_child_text(dependency, "groupId")
                        artifact = _xml_child_text(dependency, "artifactId")
                        if group and artifact:
                            dependencies.append(f"{group}:{artifact}")
                maven_projects.append({
                    "path": relative.as_posix(),
                    "group": _xml_child_text(xml_root, "groupId"),
                    "artifact": _xml_child_text(xml_root, "artifactId"),
                    "packaging": _xml_child_text(xml_root, "packaging"),
                    "modules": modules,
                    "dependencies": sorted(set(dependencies), key=str.casefold),
                })
            except (ET.ParseError, OSError, ValueError) as exc:
                warnings.append(f"Could not parse {relative.as_posix()}: {type(exc).__name__}")
    entrypoints = [path.as_posix() for path in paths if path.name.lower() in ENTRY_NAMES]
    instruction_files = sorted(
        [path.as_posix() for path in paths if path.name.lower() in {"agents.md", "claude.md", "readme.md"}]
        + [name for name in ("AGENTS.md", "CLAUDE.md") if name not in {path.as_posix() for path in paths}],
        key=str.casefold,
    )
    tests = sum(
        1 for path in paths
        if any(part.lower() in {"test", "tests", "__tests__"} for part in path.parts)
        or path.name.lower().startswith("test_")
        or path.name.lower().endswith(("test.cs", "tests.cs", ".spec.ts", ".spec.js"))
    )
    return {
        "name": root.name, "path": str(root),
        "branch": _git(root, "branch", "--show-current").strip() or "(detached)",
        "commit": _git(root, "rev-parse", "HEAD").strip(),
        "files_inventoried": len(paths), "languages": languages, "layout": layout,
        "components": components, "component_paths": component_paths,
        "manifests": [path.as_posix() for path in manifests],
        "dotnet_projects": projects, "node_packages": node_packages,
        "python_projects": python_projects, "python_requirements": python_requirements,
        "go_modules": go_modules, "maven_projects": maven_projects,
        "entrypoints": entrypoints, "instruction_files": instruction_files,
        "test_files": tests, "warnings": warnings,
    }


def _list(lines: list[str], values: list[str]) -> None:
    lines.extend(f"- {_code(value)}" for value in values)
    if not values:
        lines.append("- No se identificaron en los archivos inventariados.")


def render_repository_map(info: dict) -> str:
    """Render a compact factual map; observations are not runtime claims."""
    lines = [
        f"# Mapa del repositorio: {_display(info['name'])}", "", MAP_MARKER, "",
        "Inventario generado a partir del árbol de trabajo local y Git. Los archivos,",
        "referencias y paquetes son evidencia estática; este mapa no demuestra qué",
        "versión está desplegada ni qué rutas se ejecutan en producción.", "",
        "## Revisión analizada", "",
        f"- Ruta: {_code(info['path'])}",
        f"- Rama local: {_code(info['branch'])}",
        f"- Commit HEAD: {_code(info['commit'])}",
        f"- Archivos inventariados: {info['files_inventoried']} (versionados y no versionados no ignorados; excluye los documentos gestionados por esta herramienta).",
        "- El contenido refleja el árbol de trabajo; los cambios sin commit pueden diferir de HEAD.", "",
        "## Lenguajes", "",
    ]
    if info["languages"]:
        lines.extend(f"- {_display(name)}: {count} archivos" for name, count in info["languages"].most_common())
    else:
        lines.append("- No se identificaron archivos de código reconocidos.")
    lines.extend(["", "## Composición", ""])
    lines.extend(f"- {_code(directory)}: {count} archivos" for directory, count in sorted(info["layout"].items(), key=lambda item: (-item[1], item[0])))
    lines.extend(["", f"- Archivos de pruebas detectados por nombre/ruta: {info['test_files']}."])
    if info["components"]:
        lines.append("- Directorios de componentes detectados por nombre: "
                     + ", ".join(f"{_code(name)} ({count})" for name, count in info["components"].most_common()) + ".")
        lines.extend(["", "## Archivos de componentes candidatos", "",
                      "Clasificados únicamente por el nombre de sus carpetas:", ""])
        for label, paths in sorted(info["component_paths"].items()):
            lines.extend([f"### {_display(label)} ({len(paths)})", ""])
            _list(lines, paths[:MAX_COMPONENT_PATHS])
            if len(paths) > MAX_COMPONENT_PATHS:
                lines.append(f"- Otros {len(paths) - MAX_COMPONENT_PATHS} archivos omitidos de esta lista; consultar el árbol Git para verlos.")
            lines.append("")
    lines.extend(["", "## Manifiestos y soluciones", ""])
    _list(lines, info["manifests"])
    lines.extend(["", "## Proyectos .NET", ""])
    if not info["dotnet_projects"]:
        lines.append("- No se identificaron proyectos `.csproj` legibles.")
    for project in info["dotnet_projects"]:
        lines.extend([
            f"### {_code(project['path'])}", "",
            f"- Tipo detectado por SDK, paquetes o nombre: {_display(project['type'])}.",
            f"- SDK: {_code(project['sdk'] or 'no declarado')}.",
            f"- Framework objetivo: {_code(project['target_framework'] or 'no declarado')}.",
            f"- Framework de pruebas: {_code(project['test_framework'] or 'no detectado')}.",
            "- Referencias a proyectos: " + (", ".join(_code(x) for x in project["references"]) or "ninguna declarada") + ".",
            "- Paquetes declarados: " + (", ".join(_code(x) for x in project["packages"]) or "ninguno") + ".",
            "",
        ])
    lines.append("")
    lines.extend(["## Paquetes Node", ""])
    if not info["node_packages"]:
        lines.append("- No se identificaron `package.json` legibles.")
    for package in info["node_packages"]:
        lines.extend([
            f"### {_code(package['path'])}", "",
            f"- Nombre: {_code(package['name'] or 'no declarado')}.",
            "- Dependencias: " + (", ".join(_code(x) for x in package["dependencies"]) or "ninguna") + ".",
            "- Dependencias de desarrollo: " + (", ".join(_code(x) for x in package["dev_dependencies"]) or "ninguna") + ".",
            "",
        ])
    lines.append("")
    lines.extend(["## Proyectos Python", ""])
    if not info["python_projects"]:
        lines.append("- No se identificaron `pyproject.toml` legibles.")
        lines.append("")
    for project in info["python_projects"]:
        lines.extend([
            f"### {_code(project['path'])}", "",
            f"- Nombre: {_code(project['name'] or 'no declarado')}.",
            f"- Versión de Python requerida: {_code(project['requires_python'] or 'no declarada')}.",
            f"- Backend de construcción: {_code(project['build_backend'] or 'no declarado')}.",
            "- Dependencias declaradas: " + (", ".join(_code(x) for x in project["dependencies"]) or "ninguna") + ".",
            "",
        ])
    for requirements in info["python_requirements"]:
        lines.extend([
            f"### {_code(requirements['path'])}", "",
            "- Dependencias declaradas: " + (", ".join(_code(x) for x in requirements["dependencies"]) or "ninguna") + ".",
            "",
        ])
    lines.append("")
    lines.extend(["## Módulos Go", ""])
    if not info["go_modules"]:
        lines.append("- No se identificaron `go.mod` legibles.")
    for module in info["go_modules"]:
        lines.extend([
            f"### {_code(module['path'])}", "",
            f"- Módulo: {_code(module['module'] or 'no declarado')}.",
            "- Dependencias declaradas: " + (", ".join(_code(x) for x in module["dependencies"]) or "ninguna") + ".",
            "",
        ])
    lines.append("")
    lines.extend(["## Proyectos Maven", ""])
    if not info["maven_projects"]:
        lines.append("- No se identificaron `pom.xml` legibles.")
    for project in info["maven_projects"]:
        lines.extend([
            f"### {_code(project['path'])}", "",
            f"- Coordenadas: {_code((project['group'] or '?') + ':' + (project['artifact'] or '?'))}.",
            f"- Empaquetado: {_code(project['packaging'] or 'no declarado')}.",
            "- Módulos: " + (", ".join(_code(x) for x in project["modules"]) or "ninguno") + ".",
            "- Dependencias declaradas: " + (", ".join(_code(x) for x in project["dependencies"]) or "ninguna") + ".",
            "",
        ])
    lines.append("")
    lines.extend(["## Puntos de entrada candidatos", ""])
    _list(lines, info["entrypoints"])
    lines.extend(["", "## Documentación para agentes tras escribir el mapa", ""])
    _list(lines, info["instruction_files"])
    lines.extend([
        "", "## Uso y límites", "",
        "- Antes de actuar, leer `AGENTS.md`, `CLAUDE.md` y las instrucciones aplicables.",
        "- Verificar el código y la configuración actuales: este mapa es un índice, no una fuente de verdad runtime.",
        "- Las referencias entre proyectos son declaraciones de manifiestos; las conexiones entre repositorios requieren investigación adicional.",
        "- No se copiaron valores de configuración, credenciales ni contenido de archivos sensibles.",
    ])
    if info["warnings"]:
        lines.extend(["", "## Advertencias del inventario", ""])
        lines.extend(f"- {_display(warning)}" for warning in info["warnings"])
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines).rstrip() + "\n")


def _reference_content(existing: bytes) -> bytes:
    newline = b"\r\n" if b"\r\n" in existing else b"\n"
    block = newline.join([
        REFERENCE_START.encode(),
        b"## Mapa del repositorio",
        b"Antes de investigar o modificar este proyecto, lee [REPOSITORY_MAP.md](REPOSITORY_MAP.md).",
        b"El mapa resume evidencia estatica del repositorio; verifica siempre el codigo vigente.",
        REFERENCE_END.encode(),
    ])
    start = existing.find(REFERENCE_START.encode())
    end = existing.find(REFERENCE_END.encode())
    if start >= 0 or end >= 0:
        if start < 0 or end < start:
            raise ValueError("Incomplete repository map reference marker in agent instructions")
        return existing[:start] + block + existing[end + len(REFERENCE_END):]
    if b"REPOSITORY_MAP.md" in existing:
        return existing
    return existing + (newline * 2 if existing else b"") + block + newline


def _read_target(root: Path, name: str) -> bytes:
    target = root / name
    if target.is_symlink():
        raise ValueError(f"Refusing to write through a symlink: {target}")
    return target.read_bytes() if target.exists() else b""


def _write_if_changed(root: Path, name: str, content: bytes) -> bool:
    target = root / name
    if target.exists() and target.read_bytes() == content:
        return False
    temp_name = None
    try:
        with tempfile.NamedTemporaryFile(dir=root, prefix=".repository-map-", delete=False) as temp:
            temp_name = temp.name
            temp.write(content)
        os.replace(temp_name, target)
    finally:
        if temp_name and os.path.exists(temp_name):
            os.unlink(temp_name)
    return True


def map_repository(repo_path: str) -> dict:
    """Write the generated map and preserve existing agent instructions."""
    info = inspect_repository(repo_path)
    root = Path(info["path"])
    current_map = _read_target(root, MAP_NAME)
    if current_map and MAP_MARKER.encode() not in current_map:
        raise ValueError(f"Existing {MAP_NAME} is not generated by this tool; refusing to overwrite it")
    contents = {MAP_NAME: render_repository_map(info).encode("utf-8")}
    for name in ("AGENTS.md", "CLAUDE.md"):
        contents[name] = _reference_content(_read_target(root, name))
    changed = [name for name, content in contents.items() if _write_if_changed(root, name, content)]
    return {
        "repository": info["name"], "path": info["path"],
        "map_path": str(root / MAP_NAME), "changed_files": changed,
        "branch": info["branch"], "commit": info["commit"],
        "files_inventoried": info["files_inventoried"],
        "dotnet_projects": len(info["dotnet_projects"]),
        "node_packages": len(info["node_packages"]),
        "python_projects": len(info["python_projects"]),
        "go_modules": len(info["go_modules"]),
        "maven_projects": len(info["maven_projects"]),
        "warnings": info["warnings"],
    }
